---
###
# Creates an credential type "Ansible Tower" for backwards compatibility since this is no longer included in the Controller managed credential types.
# All "Ansible Tower" Credentials should get migrated to "Red Hat Ansible Automation Platform" Credentials.
###

- name: Load Information for missing credential Type.
  set_fact:
    ansible_automation_platform_awx_ansible_tower_credential_type_input: "{{ lookup('file', 'ansible_tower_credential_type_input.json') }}"
    ansible_automation_platform_awx_ansible_tower_credential_type_injectors: "{{ lookup('file', 'ansible_tower_credential_type_injectors.json') }}"

- name: Create missing credential Type
  ansible.controller.credential_type:
    controller_username:            "{{ controller_username }}"
    controller_password:            "{{ controller_password }}"
    controller_host:                "{{ inventory_hostname }}"
    name: "Ansible Tower"
    description: ""
    kind: cloud
    inputs: "{{ lookup('file', 'ansible_tower_credential_type_input.json') }}"
    injectors: "{{ lookup('file', 'ansible_tower_credential_type_injectors.json') }}"
    state: present
    validate_certs: false
