---
- name: Import Job Templates Debug Mode
  block:
  - name: Create Empty Error List
    set_fact:
      __ansible_automation_platform_awx_import_job_template_errors: []

  - name: Read User Assets form Export
    set_fact:
      ansible_automation_platform_awx_import_job_template_asset: "{{ lookup('file', __ansible_automation_platform_awx_import_assets_path + '/job_templates.json') |from_json |regex_replace('{{','__ANSIBLE_VARIABLE_BRACKETS_OPEN__') }}"
 
  - name: Import {{ ansible_automation_platform_awx_import_object | capitalize }} Asset Tasks
    include_tasks: import_asset.yml
    loop: "{{ ansible_automation_platform_awx_import_job_template_asset['job_templates'] }}"
    loop_control:
      loop_var: __ansible_automation_platform_awx_import_object_asset
    register: job_template_import
  when: ansible_automation_platform_awx_import_debug is defined

- name: Import {{ ansible_automation_platform_awx_import_object | capitalize }} Asset
  ansible.controller.import:
    assets:                         "{{ lookup('file', '{{ __ansible_automation_platform_awx_import_assets_path }}/job_templates.json') }}"
    controller_username:            "{{ controller_username }}"
    controller_password:            "{{ controller_password }}"
    controller_host:                "{{ inventory_hostname }}"
    validate_certs: false
  when: ansible_automation_platform_awx_import_debug is not defined
...
