---
# tasks file for awx_export_secrets

- name: Initialize empty Notification Template List
  set_fact:
    awx_export_secrets_notification_templates_list: []

- name: Export Notificaton Template Object List
  ansible.controller.export:
    tower_host: "{{ inventory_hostname }}"
    tower_password: "{{ awx_export_secrets_password }}"
    tower_username: "{{ awx_export_secrets_user }}"
    notification_templates: all
  delegate_to: localhost
  register: export_data
    #no_log: true

- name: Run AWX Database Query
  shell: "PGPASSWORD={{ awx_export_secrets_database_password }} psql -t -A -U {{ awx_export_secrets_database_user }} -d {{ awx_export_secrets_database_name }} -c \"select name,id from main_organization;\""
  register: awx_export_secrets_database_query_organizations

- set_fact:
    awx_export_secrets_organization_table: "{{ awx_export_secrets_organization_table | default({}) | combine( { item.split('|')[0] : item.split('|')[1] } ) }}"
  loop: "{{ awx_export_secrets_database_query_organizations.stdout_lines }}"

- include_tasks: process_notification_secret.yml
  loop: "{{ export_data.assets.notification_templates }}"
  loop_control:
    loop_var: awx_export_secrets_notification_template_object

- name: Generate Content Variable
  set_fact:
    file_content:
      notification_templates: "{{ awx_export_secrets_notification_templates_list }}"
  no_log: true

- block:
  - name: Create Temporary Working Directory
    ansible.builtin.tempfile:
      suffix: temp_aap_installer
      state: directory
    register: awx_export_secrets_temp_folder
    delegate_to: localhost

  - name: Write Data to Temp File
    ansible.builtin.copy:
      dest: "{{ awx_export_secrets_temp_folder.path }}/process.json"
      content: "{{ file_content |to_nice_json(indent=4) }}"
    delegate_to: localhost
    no_log: true

  - name: Generate Vault Passwort File
    ansible.builtin.lineinfile:
      path: "{{ awx_export_secrets_temp_folder.path }}/vault_password"
      line: "{{ awx_export_secrets_vault_pass }}"
      create: true
      state: present
    delegate_to: localhost
    no_log: true

  - name: Encrypt Notification Template File
    command: "ansible-vault encrypt --vault-password-file {{ awx_export_secrets_temp_folder.path }}/vault_password {{ awx_export_secrets_temp_folder.path }}/process.json"
    delegate_to: localhost
    no_log: true

  - name: Copy Final File to Destination
    ansible.builtin.copy:
      src: "{{ awx_export_secrets_temp_folder.path }}/process.json"
      dest: "{{ awx_export_secrets_export_path }}/notification_templates.json"
      remote_src: true
    delegate_to: localhost

  always:
  - name: Remove Temporary Working Directory
    file:
      path: "{{ awx_export_secrets_temp_folder.path }}"
      state: absent
    delegate_to: localhost


