---
- debug: 
    msg: "Credential Name: {{ awx_export_secrets_notification_template_object.name }}"

- set_fact:
    awx_export_secrets_query_object_name: "{{ awx_export_secrets_notification_template_object.name |replace(\"'\",\"''\") }}"

- name: Run AWX Database Query
  shell: "PGPASSWORD={{ awx_export_secrets_database_password }} psql -t -A -U {{ awx_export_secrets_database_user }} -d {{ awx_export_secrets_database_name }} -c \"select id,notification_configuration from main_notificationtemplate WHERE name = '{{ awx_export_secrets_query_object_name }}' and organization_id = '{{ awx_export_secrets_organization_table[awx_export_secrets_notification_template_object.organization.name] }}';\""
  register: awx_export_secrets_database_query
  no_log: true

- name: Process AWX Credential List
  awxnotificationsecret:
    kid: '{{ awx_export_secrets_database_query.stdout.split("|")[0] }}'
    data: '\"{{ awx_export_secrets_database_query.stdout.split("|")[1] }}\"'
    credential: "'{{ awx_export_secrets_notification_template_object }}'"
    secret: "{{ awx_export_secrets_tower_secret }}"
  register: awx_export_secrets_plugin
    
- name: Append Credential to List
  set_fact:
    awx_export_secrets_notification_templates_list: "{{ awx_export_secrets_notification_templates_list + [awx_export_secrets_plugin['result']] }}"
  no_log: true
