---
- name: Playbook to configure AAP controller post-installation
  hosts: localhost
  vars_files:
    - "vault.yml"
  connection: local
  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./vars
        extensions: ["yml", "json"]
  tasks:
    - name: Create Organizations
      ansible.builtin.include_role:
        name: infra.controller_configuration.organizations

    - name: Create Teams
      ansible.builtin.include_role:
        name: infra.controller_configuration.teams

    - name: Create users
      ansible.builtin.include_role:
        name: infra.controller_configuration.users

    - name: Create Credential Types
      ansible.builtin.include_role:
        name: infra.controller_configuration.credential_types
        
    - name: Create Credentials
      ansible.builtin.include_role:
        name: infra.controller_configuration.credentials

    - name: Create Notification Templates
      ansible.builtin.include_role:
        name: infra.controller_configuration.notification_templates
        
    - name: Create Projects
      ansible.builtin.include_role:
        name: infra.controller_configuration.projects

    - name: Create inventories
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventories
    
    - name: Create Hosts
      ansible.builtin.include_role:
        name: infra.controller_configuration.hosts

    - name: Create Hosts
      ansible.builtin.include_role:
        name: infra.controller_configuration.groups
   
    - name: Create inventory sources
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventory_sources

    - name: Create Job Templates
      ansible.builtin.include_role:
        name: infra.controller_configuration.job_templates
    
    - name: Create Schedules
      ansible.builtin.include_role:
        name: infra.controller_configuration.schedules
