---
- name: Update LDAP User DN on Ansible Automation Platform
  community.postgresql.postgresql_query:
    db: "{{ ansible_automation_platform_awx_import_aap_database_name }}"
    login_user: "{{ ansible_automation_platform_awx_import_aap_database_user }}"
    login_password: "{{ ansible_automation_platform_awx_import_aap_database_password }}"
    query: "UPDATE main_profile SET ldap_dn = '{{ user_ldap_table[ansible_automation_platform_awx_import_user_id.value] }}' WHERE user_id = '{{ ansible_automation_platform_awx_import_user_id.key }}';"
  loop: "{{ user_ldap_table | dict2items }}"
  loop_control:
    loop_var: __user_ldap_entry
  when: __user_ldap_entry.key == ansible_automation_platform_awx_import_user_id.value
